version: '3.8'

services:
  db:
    restart: always
    environment:
      MYSQL_DATABASE: 'momentum'
      MYSQL_USER: ${MOM_DATABASE_USER}
      MYSQL_PASSWORD: ${MOM_DATABASE_PW}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}

  api:
    image: docker.pkg.github.com/momentum-mod/website/mmod-website:staging
    volumes:
      - ./server/public/img/maps:/app/server/public/img/maps
      - ./server/public/maps:/app/server/public/maps
      - ./server/public/runs:/app/server/public/runs

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: unless-stopped
    links:
      - prometheus:prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    ports:
      - '${GRAFANA_PORT}:300'
